WINDOW_WIDTH = 800
WINDOW_HEIGHT = 600
FPS = 60

# Colours
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)

BUTTON_RADIUS = 20
BUTTON_GAP_SIZE = 15
BUTTONS_IN_ROW = 13
BUTTON_ROWS = 2
BUTTON_CIRCLE_THICKNESS = 3

LETTER_A_ASCII_CODE = 65

WORDS = [
    "UMBRELLA",
    "RAINBOW",
    "TRAIN",
    "MUSICAL",
    "GINGER",
    "WINDOW",
    "COMPUTER",
    "HAPPINESS",
    "BEAUTIFUL",
    "DOMESTIC",
    "DONKEY",
    "PHENOMENON",
    "MYSTERY",
    "PICTURE",
    "PAINTING",
    "MELODY",
    "INSTRUMENT",
    "FREEDOM",
    "HYPERBOLICAL",
    "SAVIOUR",
    "HEROINE",
    "GUITAR",
    "STRATEGY",
    "BUTTON",
    "EARTH",
    "BREATHE",
    "EXHALE",
    "HUSBAND",
    "CHILDREN"
]
