from enum import Enum

from settings import WINDOW_HEIGHT, WINDOW_WIDTH


class CastleState(Enum):
    FULLY_RESTORED = 100
    DAMAGED = 50
    SEVERELY_DAMAGED = 25


class CastlePosition(Enum):
    FULLY_RESTORED = (WINDOW_WIDTH - 430, WINDOW_HEIGHT - 500)
    DAMAGED = (WINDOW_WIDTH - 430, WINDOW_HEIGHT - 490)
    SEVERELY_DAMAGED = (WINDOW_WIDTH - 425, WINDOW_HEIGHT - 427)


class TowerState(Enum):
    FULLY_RESTORED = 100
    DAMAGED = 50
    SEVERELY_DAMAGED = 25


CASTLE_IMAGE_SCALE = 0.3
TOWER_IMAGE_SCALE = 0.3
BULLET_IMAGE_SCALE = 0.075
BULLET_SPEED = 100
BULLET_DAMAGE = 25
TOWER_SHOOT_BULLET_DELAY = 1500
