from enum import Enum


class ModelAsset(Enum):
    BAGUETTE = "baguette"
    BAGUETTE_HALF = "baguette_half"
    BAGUETTE_SLICE = "baguette_slice"
    BREAD = "bread"
    BREAD_HALF = "bread_half"
    BREAD_ROLL = "bread_roll"
    BREAD_SLICE = "bread_slice"
    CAKE_BIRTHDAY = "cake_birthday"
    CAKE_BIRTHDAY_CUT = "cake_birthday_cut"
    CAKE_BIRTHDAY_SLICE = "cake_birthday_slice"
    CAKE_CHOCOLATE = "cake_chocolate"
    CAKE_CHOCOLATE_CUT = "cake_chocolate_cut"
    CAKE_CHOCOLATE_SLICE = "cake_chocolate_slice"
    CAKE_STRAWBERRY = "cake_strawberry"
    CAKE_STRAWBERRY_CUT = "cake_strawberry_cut"
    CAKE_STRAWBERRY_SLICE = "cake_strawberry_slice"
    CINNAMON_ROLL = "cinnamon_roll"
    COOKIE = "cookie"
    CROISSANT = "croissant"
    CUPCAKE = "cupcake"
    DONUT = "donut"
    DONUT_CHOCOLATE = "donut_chocolate"
    DONUT_PINK = "donut_pink"
    MUFFIN = "muffin"
    PIE_APPLE = "pie_apple"
    PIE_APPLE_CUT = "pie_apple_cut"
    PIE_APPLE_SLICE = "pie_apple_slice"
    PIE_CHERRY = "pie_cherry"
    PIE_CHERRY_CUT = "pie_cherry_cut"
    PIE_CHERRY_SLICE = "pie_cherry_slice"
    WAFFLE = "waffle"
    WAFFLE_STACKED = "waffle_stacked"
