TILES_ROWS = 15
TILES_COLUMNS = 15
TILE_SIZE = 48
SIDE_PANEL_WIDTH = 300
MAP_WIDTH = TILES_ROWS * TILE_SIZE
MAP_HEIGHT = TILES_COLUMNS * TILE_SIZE
FPS = 60

# Images paths
MAP_PATH = "assets/levels/level.png"

# JSONs paths
MAP_METADATA_PATH = "assets/levels/level.tmj"

HEALTH = 100
MONEY = 650
