[package]
name = "sonic-runner-with-rust-and-bevy"
version = "0.1.0"
edition = "2024"
authors = ["Dominik Stefancik <dstefancik@gmail.com>"]

[dependencies]
bevy = { version="0.19.1", features = ["mp3", "wav"] }
rand = "0.10.3"

# Faster compile times during development
[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
