from enum import Enum


class CastleState(Enum):
    FULLY_RESTORED = 100
    DAMAGED = 50
    SEVERELY_DAMAGED = 25


class TowerState(Enum):
    FULLY_RESTORED = 100
    DAMAGED = 50
    SEVERELY_DAMAGED = 25


CASTLE_IMAGE_SCALE = 0.3
TOWER_IMAGE_SCALE = 0.3
BULLET_IMAGE_SCALE = 0.075
BULLET_SPEED = 100
BULLET_DAMAGE = 25
TOWER_SHOOT_BULLET_DELAY = 1500
