from enum import Enum


class FileFormat(Enum):
    JPG = "jpg"
    PNG = "png"


class ImageAssetGroup(Enum):
    FLAG = "flag"
    SAW = "saw"
    SAW_CHAIN = "saw_chain"
    FLOOR_SPIKE = "floor_spike"
    LEVEL_PALMS = "palms"
    CANDLE = "candle"
    CANDLE_LIGHT = "candle_light"
    WINDOW = "window"
    BIG_CHAIN = "big_chain"
    SMALL_CHAIN = "small_chain"
    PLAYER = "player"
    HELICOPTER = "helicopter"
    BOAT = "boat"
    SPIKED_BALL = "spiked_ball"
    SPIKED_CHAIN = "spiked_chain"
    TOOTH = "tooth"
    SHELL = "shell"
    PEARL = "pearl"
    ITEMS = "items"
    PARTICLE = "particle"
    HEART = "heart"
    COIN = "coin"
    WATER_TOP = "water_top"
    WATER_BODY = "water_body"
    BACKGROUND_TILES = "bg_tiles"
    CLOUD_SMALL = "cloud_small"
    CLOUD_LARGE = "cloud_large"
    OVERWORLD_PALM = "palm"
    OVERWORLD_WATER = "water"
    STONE = "stone"
    PATH = "path"
    ICON = "icon"
