from os.path import join

# Images paths
BIRD_IMAGE_PATH = join("assets", "images", "bird.png")

BIRD_FRAME_SIZE = 32
BIRD_FRAME_SCALE = 1.5
BIRD_FRAMES_COUNT = 8
BIRD_ANIMATION_COOLDOWM = 50 # 50 miliseconds
BIRD_START_FLYING_ONCE_THRESHOLD = 2000
BIRD_START_ROTATING_THRESHOLD = 4000
BIRD_MOVEMENT_LEFT_TO_RIGHT = 1
BIRD_MOVEMENT_RIGHT_TO_LEFT = -1

MAX_BIRDS_COUNT = 1
