pub mod camera;
pub mod controls;
pub mod default;
pub mod food;
pub mod game;
pub mod score;
pub mod shared;
pub mod snake;
pub mod window;

pub use camera::CameraPlugin;
pub use controls::ControlsPlugin;
pub use default::default_plugin;
pub use food::FoodPlugin;
pub use game::GamePlugin;
pub use score::ScorePlugin;
pub use shared::SharedPlugin;
pub use snake::SnakePlugin;
pub use window::WindowPlugin;
