WINDOW_WIDTH = 400
WINDOW_HEIGHT = 600
FPS = 60

# Images paths
BACKGROUND_IMAGE_PATH = "assets/images/background.png"

# Sounds paths
BACKGROUND_MUSIC_SOUND_PATH = "assets/sounds/background_music.mp3"

BACKGROUND_IMAGE_HEIGHT = 600
SCORE_PANEL_HEIGHT = 20

# Colours
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
PANEL_COLOR = (153, 217, 234)

VERTICAL_SCROLL_THRESHOLD = 200
WINDOW_FADE_COUNTER_TRANSITION = 5 # the transition will happen by 5 pixels
WINDOW_FADE_RECTANGLE_COUNT = 6
