WINDOW_WIDTH = 400
WINDOW_HEIGHT = 600
FPS = 60

# Images paths
BACKGROUND_IMAGE_PATH = "assets/images/background.png"

BACKGROUND_IMAGE_HEIGHT = 600

# Colours
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)

VERTICAL_SCROLL_THRESSHOLD = 200
WINDOW_FADE_COUNTER_TRANSITION = 5 # the transition will happen by 5 pixels
WINDOW_FADE_RECTANGLE_COUNT = 6
